version: '3.7'

services:
  db:
    image: postgres
    container_name: pg
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=board
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    restart: always
    container_name: backend
    command: bash -c "python manage.py migrate --run-syncdb && python manage.py loaddata init && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  celery-worker:
    build: .
    container_name: worker
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/src/app
    links:
      - redis
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    container_name: beat
    command: celery -A config beat -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379